### ISSUE TITLE
Photoflow crashes when you zoom out very fast on Windows 10 (64 bit)

### ISSUE THREAD

**Issue by SilvioGrosso** [aferrero2707/PhotoFlow#200]
Hello,

I have tried on Windows 10 (64 bit) the version:
photoflow-w64-20191023_2016-git-stable-d646102fdbfc9a11ab7a22bda5fd4dff69f52498

It always crashes when you zoom out very fast on Windows: no matter what NEF D700 image I try.
I have thought this bug was fixed, hence my testing...
The backtrace is similar to the previous similar crash of mine with the Unsharp mask branch.

BTW, when you zoom out Photoflow behaves  oddly about the image which is currently visualized while zooming. It looks as though it even tries to zoom in the image while I am instead zooming out.

Here is the backtrace:
Thread 7 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 11768.0x31b4]
0x0000000067f0b086 in ?? ()
(gdb) thread apply all bt

Thread 54 (Thread 11768.0x2bbc):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 53 (Thread 11768.0x2fd8):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 36 (Thread 11768.0x1b5c):
#0  0x00007ff80a9dcc14 in ?? ()
#1  0x00007ff8083b7ff7 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 11768.0x256c):
#0  0x00007ff80a9dcc14 in ?? ()
#1  0x00007ff8083b7ff7 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 8 (Thread 11768.0x23b0):
#0  0x00007ff808939a84 in ?? ()
#1  0x00007ff80a02260d in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 11768.0x31b4):
#0  0x0000000067f0b086 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
---Type <return> to continue, or q <return> to quit---

Thread 6 (Thread 11768.0x19e4):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 11768.0x26a8):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 4 (Thread 11768.0x2594):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 3 (Thread 11768.0x1e80):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 11768.0x26b0):
#0  0x00007ff80a9dfa54 in ?? ()
#1  0x00007ff80a974060 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 11768.0x183c):
#0  0x000000006f74e40a in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by SilvioGrosso** [comment]
Tried the same steps on Linux too (Kubuntu 19.10 - KDE Desktop).
It works fine: No crash whatsoever when zooming out very fast.
Therefore, it is only Windows 10 (64 bit) which is concerned: good for us 👍

**Comment by SilvioGrosso** [comment]
Just tested with the latest version: PhotoFlow HEAD-98caa (2019-10-25)
The crash is no longer present while zooming out fast on Windows 10 - 64 bit.
I close this bug as solved :-)
